[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Specific configuration for upload functions - 30 second timeout
[functions."upload*"]
  timeout = 30

# CORS globale per tutte le funzioni
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"