[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"


[functions."upload"]
 binary_media_types = ["application/octet-stream"]

[functions."upload-chunk"]
  binary_media_types = ["application/octet-stream"]

# CORS globale per tutte le funzioni
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"